-- ============================================================
-- RailSafari Database Schema - Tables Definition
-- Database: Oracle Database
-- ============================================================

-- 1. USERS Table
CREATE TABLE USERS (
    USER_ID NUMBER PRIMARY KEY,
    FULL_NAME VARCHAR2(100) NOT NULL,
    PHONE VARCHAR2(15) UNIQUE NOT NULL,
    IRCTC_NUMBER VARCHAR2(30),
    EMAIL VARCHAR2(100) UNIQUE NOT NULL,
    PASSWORD_HASH VARCHAR2(255) NOT NULL,
    VERIFICATION_STATUS VARCHAR2(20) DEFAULT 'VERIFIED',
    CREATED_AT DATE DEFAULT SYSDATE
);

-- 2. STATION Table
CREATE TABLE STATION (
    STATION_ID NUMBER PRIMARY KEY,
    STATION_CODE VARCHAR2(10) UNIQUE NOT NULL,
    STATION_NAME VARCHAR2(100) NOT NULL,
    CITY VARCHAR2(100) NOT NULL,
    STATE VARCHAR2(100) NOT NULL
);

-- 3. TRAIN Table
CREATE TABLE TRAIN (
    TRAIN_ID NUMBER PRIMARY KEY,
    TRAIN_NUMBER VARCHAR2(10) UNIQUE NOT NULL,
    TRAIN_NAME VARCHAR2(100) NOT NULL,
    TRAIN_TYPE VARCHAR2(50) DEFAULT 'EXPRESS'
);

-- 4. TRAIN_ROUTE Table
CREATE TABLE TRAIN_ROUTE (
    ROUTE_ID NUMBER PRIMARY KEY,
    TRAIN_ID NUMBER NOT NULL,
    STATION_ID NUMBER NOT NULL,
    STOP_NUMBER NUMBER NOT NULL,
    ARRIVAL_TIME VARCHAR2(10),
    DEPARTURE_TIME VARCHAR2(10),
    DISTANCE_KM NUMBER(8,2)
);

-- 5. SCHEDULE Table
CREATE TABLE SCHEDULE (
    SCHEDULE_ID NUMBER PRIMARY KEY,
    TRAIN_ID NUMBER NOT NULL,
    JOURNEY_DATE DATE NOT NULL,
    SOURCE_STATION_ID NUMBER NOT NULL,
    DESTINATION_STATION_ID NUMBER NOT NULL,
    STATUS VARCHAR2(20) DEFAULT 'AVAILABLE'
);

-- 6. COACH Table
CREATE TABLE COACH (
    COACH_ID NUMBER PRIMARY KEY,
    TRAIN_ID NUMBER NOT NULL,
    COACH_NUMBER VARCHAR2(10) NOT NULL,
    CLASS_TYPE VARCHAR2(20) NOT NULL,
    TOTAL_SEATS NUMBER NOT NULL
);

-- 7. SEAT Table
CREATE TABLE SEAT (
    SEAT_ID NUMBER PRIMARY KEY,
    COACH_ID NUMBER NOT NULL,
    SEAT_NUMBER VARCHAR2(10) NOT NULL,
    SEAT_TYPE VARCHAR2(20) DEFAULT 'WINDOW',
    SEAT_STATUS VARCHAR2(20) DEFAULT 'AVAILABLE'
);

-- 8. BOOKING Table
CREATE TABLE BOOKING (
    BOOKING_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    SCHEDULE_ID NUMBER NOT NULL,
    BOOKING_DATE DATE DEFAULT SYSDATE,
    QUOTA VARCHAR2(20) DEFAULT 'GENERAL',
    TOTAL_FARE NUMBER(10,2) NOT NULL,
    BOOKING_STATUS VARCHAR2(20) DEFAULT 'CONFIRMED',
    PNR VARCHAR2(20) UNIQUE NOT NULL
);

-- 9. PASSENGER Table
CREATE TABLE PASSENGER (
    PASSENGER_ID NUMBER PRIMARY KEY,
    BOOKING_ID NUMBER NOT NULL,
    PASSENGER_NAME VARCHAR2(100) NOT NULL,
    AGE NUMBER NOT NULL,
    GENDER VARCHAR2(10),
    SEAT_ID NUMBER
);

-- 10. PAYMENT Table
CREATE TABLE PAYMENT (
    PAYMENT_ID NUMBER PRIMARY KEY,
    BOOKING_ID NUMBER NOT NULL,
    PAYMENT_DATE DATE DEFAULT SYSDATE,
    AMOUNT NUMBER(10,2) NOT NULL,
    PAYMENT_METHOD VARCHAR2(30) DEFAULT 'UPI',
    PAYMENT_STATUS VARCHAR2(20) DEFAULT 'SUCCESS'
);

-- 11. CANCELLATION Table
CREATE TABLE CANCELLATION (
    CANCELLATION_ID NUMBER PRIMARY KEY,
    BOOKING_ID NUMBER NOT NULL,
    CANCELLATION_DATE DATE DEFAULT SYSDATE,
    REASON VARCHAR2(255),
    REFUND_AMOUNT NUMBER(10,2)
);
