-- ============================================================
-- RailSafari Database Schema - Foreign Keys & Constraints
-- Database: Oracle Database
-- ============================================================

-- TRAIN_ROUTE Constraints
ALTER TABLE TRAIN_ROUTE ADD CONSTRAINT FK_ROUTE_TRAIN FOREIGN KEY (TRAIN_ID) REFERENCES TRAIN(TRAIN_ID);
ALTER TABLE TRAIN_ROUTE ADD CONSTRAINT FK_ROUTE_STATION FOREIGN KEY (STATION_ID) REFERENCES STATION(STATION_ID);

-- SCHEDULE Constraints
ALTER TABLE SCHEDULE ADD CONSTRAINT FK_SCHEDULE_TRAIN FOREIGN KEY (TRAIN_ID) REFERENCES TRAIN(TRAIN_ID);
ALTER TABLE SCHEDULE ADD CONSTRAINT FK_SCHEDULE_SRC FOREIGN KEY (SOURCE_STATION_ID) REFERENCES STATION(STATION_ID);
ALTER TABLE SCHEDULE ADD CONSTRAINT FK_SCHEDULE_DEST FOREIGN KEY (DESTINATION_STATION_ID) REFERENCES STATION(STATION_ID);

-- COACH Constraints
ALTER TABLE COACH ADD CONSTRAINT FK_COACH_TRAIN FOREIGN KEY (TRAIN_ID) REFERENCES TRAIN(TRAIN_ID);

-- SEAT Constraints
ALTER TABLE SEAT ADD CONSTRAINT FK_SEAT_COACH FOREIGN KEY (COACH_ID) REFERENCES COACH(COACH_ID);
ALTER TABLE SEAT ADD CONSTRAINT CHK_SEAT_STATUS CHECK (SEAT_STATUS IN ('AVAILABLE', 'BOOKED', 'RESERVED'));

-- BOOKING Constraints
ALTER TABLE BOOKING ADD CONSTRAINT FK_BOOKING_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID);
ALTER TABLE BOOKING ADD CONSTRAINT FK_BOOKING_SCHEDULE FOREIGN KEY (SCHEDULE_ID) REFERENCES SCHEDULE(SCHEDULE_ID);
ALTER TABLE BOOKING ADD CONSTRAINT CHK_BOOKING_STATUS CHECK (BOOKING_STATUS IN ('CONFIRMED', 'CANCELLED', 'WAITLISTED'));

-- PASSENGER Constraints
ALTER TABLE PASSENGER ADD CONSTRAINT FK_PASSENGER_BOOKING FOREIGN KEY (BOOKING_ID) REFERENCES BOOKING(BOOKING_ID);
ALTER TABLE PASSENGER ADD CONSTRAINT FK_PASSENGER_SEAT FOREIGN KEY (SEAT_ID) REFERENCES SEAT(SEAT_ID);
ALTER TABLE PASSENGER ADD CONSTRAINT CHK_PASSENGER_AGE CHECK (AGE > 0 AND AGE <= 120);
ALTER TABLE PASSENGER ADD CONSTRAINT CHK_PASSENGER_GENDER CHECK (GENDER IN ('MALE', 'FEMALE', 'OTHER'));

-- PAYMENT Constraints
ALTER TABLE PAYMENT ADD CONSTRAINT FK_PAYMENT_BOOKING FOREIGN KEY (BOOKING_ID) REFERENCES BOOKING(BOOKING_ID);
ALTER TABLE PAYMENT ADD CONSTRAINT CHK_PAYMENT_STATUS CHECK (PAYMENT_STATUS IN ('SUCCESS', 'FAILED', 'REFUNDED'));

-- CANCELLATION Constraints
ALTER TABLE CANCELLATION ADD CONSTRAINT FK_CANCEL_BOOKING FOREIGN KEY (BOOKING_ID) REFERENCES BOOKING(BOOKING_ID);
