-- ============================================================
-- RailSafari Database Schema - Sequences
-- Database: Oracle Database
-- ============================================================

CREATE SEQUENCE USER_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE STATION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE TRAIN_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE ROUTE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SCHEDULE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE COACH_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEAT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE BOOKING_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE PASSENGER_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE PAYMENT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE CANCELLATION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
