-- ============================================================
-- RailSafari Database Schema - Sample Seed Data
-- Database: Oracle Database
-- ============================================================

-- Stations
INSERT INTO STATION (STATION_ID, STATION_CODE, STATION_NAME, CITY, STATE) VALUES (1, 'ERS', 'ERNAKULAM JUNCTION', 'KOCHI', 'KERALA');
INSERT INTO STATION (STATION_ID, STATION_CODE, STATION_NAME, CITY, STATE) VALUES (2, 'TVC', 'THIRUVANANTHAPURAM CENTRAL', 'THIRUVANANTHAPURAM', 'KERALA');
INSERT INTO STATION (STATION_ID, STATION_CODE, STATION_NAME, CITY, STATE) VALUES (3, 'CLT', 'KOZHIKODE', 'KOZHIKODE', 'KERALA');
INSERT INTO STATION (STATION_ID, STATION_CODE, STATION_NAME, CITY, STATE) VALUES (4, 'CAN', 'KANNUR', 'KANNUR', 'KERALA');
INSERT INTO STATION (STATION_ID, STATION_CODE, STATION_NAME, CITY, STATE) VALUES (5, 'MAQ', 'MANGALURU CENTRAL', 'MANGALURU', 'KARNATAKA');

-- Trains
INSERT INTO TRAIN (TRAIN_ID, TRAIN_NUMBER, TRAIN_NAME, TRAIN_TYPE) VALUES (1, '12625', 'KERALA EXPRESS', 'EXPRESS');
INSERT INTO TRAIN (TRAIN_ID, TRAIN_NUMBER, TRAIN_NAME, TRAIN_TYPE) VALUES (2, '16347', 'MANGALURU EXPRESS', 'EXPRESS');
INSERT INTO TRAIN (TRAIN_ID, TRAIN_NUMBER, TRAIN_NAME, TRAIN_TYPE) VALUES (3, '16603', 'MAVELI EXPRESS', 'SUPERFAST');

-- Schedules
INSERT INTO SCHEDULE (SCHEDULE_ID, TRAIN_ID, JOURNEY_DATE, SOURCE_STATION_ID, DESTINATION_STATION_ID, STATUS) VALUES (1, 1, TO_DATE('2026-09-24', 'YYYY-MM-DD'), 1, 2, 'AVAILABLE');
INSERT INTO SCHEDULE (SCHEDULE_ID, TRAIN_ID, JOURNEY_DATE, SOURCE_STATION_ID, DESTINATION_STATION_ID, STATUS) VALUES (2, 1, TO_DATE('2026-09-25', 'YYYY-MM-DD'), 1, 2, 'AVAILABLE');
INSERT INTO SCHEDULE (SCHEDULE_ID, TRAIN_ID, JOURNEY_DATE, SOURCE_STATION_ID, DESTINATION_STATION_ID, STATUS) VALUES (3, 2, TO_DATE('2026-09-24', 'YYYY-MM-DD'), 1, 5, 'AVAILABLE');
INSERT INTO SCHEDULE (SCHEDULE_ID, TRAIN_ID, JOURNEY_DATE, SOURCE_STATION_ID, DESTINATION_STATION_ID, STATUS) VALUES (4, 3, TO_DATE('2026-09-26', 'YYYY-MM-DD'), 2, 5, 'AVAILABLE');

-- Coaches
INSERT INTO COACH (COACH_ID, TRAIN_ID, COACH_NUMBER, CLASS_TYPE, TOTAL_SEATS) VALUES (1, 1, 'A1', '3A', 64);
INSERT INTO COACH (COACH_ID, TRAIN_ID, COACH_NUMBER, CLASS_TYPE, TOTAL_SEATS) VALUES (2, 2, 'S1', 'SL', 72);
INSERT INTO COACH (COACH_ID, TRAIN_ID, COACH_NUMBER, CLASS_TYPE, TOTAL_SEATS) VALUES (3, 2, 'B1', '2A', 54);
INSERT INTO COACH (COACH_ID, TRAIN_ID, COACH_NUMBER, CLASS_TYPE, TOTAL_SEATS) VALUES (4, 3, 'S1', 'SL', 72);
INSERT INTO COACH (COACH_ID, TRAIN_ID, COACH_NUMBER, CLASS_TYPE, TOTAL_SEATS) VALUES (5, 3, 'C1', 'CC', 78);
INSERT INTO COACH (COACH_ID, TRAIN_ID, COACH_NUMBER, CLASS_TYPE, TOTAL_SEATS) VALUES (6, 3, 'C2', 'CC', 78);

-- Users
INSERT INTO USERS (USER_ID, FULL_NAME, PHONE, IRCTC_NUMBER, EMAIL, PASSWORD_HASH, VERIFICATION_STATUS) VALUES (1, 'ARJUN MENON', '9876543210', 'IRCTC_ARJUN', 'arjun@gmail.com', '5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8', 'VERIFIED');
INSERT INTO USERS (USER_ID, FULL_NAME, PHONE, IRCTC_NUMBER, EMAIL, PASSWORD_HASH, VERIFICATION_STATUS) VALUES (2, 'ANANYA NAIR', '9876543211', 'IRCTC_ANANYA', 'ananya@gmail.com', '5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8', 'VERIFIED');
INSERT INTO USERS (USER_ID, FULL_NAME, PHONE, IRCTC_NUMBER, EMAIL, PASSWORD_HASH, VERIFICATION_STATUS) VALUES (3, 'RAHUL KRISHNAN', '9876543212', 'IRCTC_RAHUL', 'rahul@gmail.com', '5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8', 'VERIFIED');

COMMIT;
