-- ============================================================
-- RailSafari Database Schema - Views Definition
-- Database: Oracle Database
-- ============================================================

-- 1. AVAILABLE_TRAINS View
CREATE OR REPLACE VIEW AVAILABLE_TRAINS AS
SELECT
    S.SCHEDULE_ID,
    T.TRAIN_NUMBER,
    T.TRAIN_NAME,
    SS.STATION_NAME AS SOURCE_STATION,
    DS.STATION_NAME AS DESTINATION_STATION,
    S.JOURNEY_DATE,
    S.STATUS
FROM SCHEDULE S
JOIN TRAIN T ON S.TRAIN_ID = T.TRAIN_ID
JOIN STATION SS ON S.SOURCE_STATION_ID = SS.STATION_ID
JOIN STATION DS ON S.DESTINATION_STATION_ID = DS.STATION_ID;

-- 2. USER_BOOKINGS View
CREATE OR REPLACE VIEW USER_BOOKINGS AS
SELECT
    B.BOOKING_ID,
    U.FULL_NAME,
    U.EMAIL,
    B.PNR,
    T.TRAIN_NUMBER,
    T.TRAIN_NAME,
    B.QUOTA,
    B.TOTAL_FARE,
    B.BOOKING_STATUS,
    B.BOOKING_DATE
FROM BOOKING B
JOIN USERS U ON B.USER_ID = U.USER_ID
JOIN SCHEDULE S ON B.SCHEDULE_ID = S.SCHEDULE_ID
JOIN TRAIN T ON S.TRAIN_ID = T.TRAIN_ID;

-- 3. TRAIN_SEAT_AVAILABILITY View
CREATE OR REPLACE VIEW TRAIN_SEAT_AVAILABILITY AS
SELECT
    T.TRAIN_NUMBER,
    T.TRAIN_NAME,
    C.COACH_NUMBER,
    C.CLASS_TYPE,
    COUNT(S.SEAT_ID) AS TOTAL_SEATS,
    SUM(
        CASE
            WHEN S.SEAT_STATUS = 'AVAILABLE' THEN 1
            ELSE 0
        END
    ) AS AVAILABLE_SEATS
FROM TRAIN T
JOIN COACH C ON T.TRAIN_ID = C.TRAIN_ID
JOIN SEAT S ON C.COACH_ID = S.COACH_ID
GROUP BY
    T.TRAIN_NUMBER,
    T.TRAIN_NAME,
    C.COACH_NUMBER,
    C.CLASS_TYPE;
